### PR TITLE
Deeponet multi-output fix

### LINKED ISSUE #9: DeepOnet Multiple output
```julia
u = ones(Float32, 10, 10, 5)
v = ones(Float32, 1, 10, 5)
deeponet = DeepONet(; branch = (10, 10, 10), trunk = (1, 10, 10))
ps, st = Lux.setup(Random.default_rng(), deeponet)

y, st_ = deeponet((u, v), ps, st)
@test size(y) == (10, 5)
```

Now the output only for one feature solution with dropping one dim (1, 10, 5) to (10, 5). It is not dim for multiple output. 
It need additional dim `(output_dim, 10, 5) `
My suggestion and easy way is add linear layer as option, how it has done here `src/neural_operators.jl` https://github.com/SciML/NeuralPDE.jl/pull/806/commits/30a5134e20862a7159f87e55010bbea73d0ed061#diff-3623c72624d6f36cc808e510588bfe6ed4872162fdce6e12b69408856c038c5d

```julia
deeponet = DeepONet(; branch = (10, 10, 10), trunk = (1, 10, 10), liner =(10, output_dim))
```

### PR DESCRIPTION
**Pull request by ayushinav**
Closes #9

### CODE REVIEW

**Comment by avik-pal** [comment]
Test failures are real. Ignore the Aqua failures for now.

File: src/deeponet.jl [hunk 1]
```diff
@@ -47,7 +50,7 @@ function DeepONet(; branch=(64, 32, 32, 16), trunk=(1, 8, 8, 16),
     trunk_net = Chain([Dense(trunk[i] => trunk[i + 1], trunk_activation)
                        for i in 1:(length(trunk) - 1)]...)
 
-    return DeepONet(branch_net, trunk_net)
+    return DeepONet(branch_net, trunk_net; additional=additional)
```
Comment (avik-pal) [inline src/deeponet.jl:53]:
```suggestion
    return DeepONet(branch_net, trunk_net; additional)
```

**Review by avik-pal — APPROVED** [review]
